DATA_PATH = '../data/'

SOS_TOKEN = 'SOS'
EOS_TOKEN = 'EOS'
UNK_TOKEN = 'UNK'
PAD_TOKEN = 'PAD'

SOS_TOKEN_IDX = 0
EOS_TOKEN_IDX = 1
UNK_TOKEN_IDX = 2
PAD_TOKEN_IDX = 3

TRAINER_STATE_NAME = 'trainer_states.pt'
MODEL_NAME = 'model.pt'
KEY_SEQUENCE = 'sequence'
KEY_LENGTH = 'length'
 
DEBUG = True
